### PR TITLE
Port to python3

### PR DESCRIPTION
**Pull request by samueloph**
First attempt at porting weevely to python3
https://github.com/epinna/weevely3/issues/102

I understand @OwenChia started working on this at https://github.com/OwenChia/weevely3 but it looks like some other improvement were added and it's not ready.

I decided to run 2to3 on the source code and fix the false positives that I find, this PR is the result of it.

There are a couple of changes that I'm not sure about so testing and reviews will need to be done, I hope this helps porting weevely3 to python3 as it doesn't looks like much work is needed.

I help maintain weevely3 on Debian/Kali and having it ported to python3 is of my interest as Debian is dropping python2 packages.

I allowed edits in the fork's branch of this PR so you can update it if it suits you better.

Regards,

### CODE REVIEW

**Comment by epinna** [comment]
Thanks, I'll check it asap.

**Comment by epinna** [comment]
Dear Samuel,

I'm sorry to kill PR this but I needed to squash my further commits against yoursso I rebased and I don't want to --force my changes on your repo.

You can find the port to Python 3 at [this branch ](https://github.com/epinna/weevely3/tree/Debian-master). The test suits passes, I still need to apply some cosmetic changes and then I'll release a new version in the next days. Feel free to use it to test it works, if you feel it's appropriate.

I'll notify you here once is ready.

**Comment by epinna** [comment]
As promised, https://github.com/epinna/weevely3/releases/tag/v4.0.0

**Comment by samueloph** [comment]
thank you @epinna !!!

I' m happy to know that my patches were useful.

**Pull request closed without merging**
