### PR TITLE
update terminal.py fix mac osx error

### PR DESCRIPTION
**Pull request by c4bbage**
fix mac osx error

### CODE REVIEW

**Comment by epinna** [comment]
What type of errors are you trying to suppress? Could they be fixed in a more elegant way? Let me try it on a mac osx to check this.

**Comment by c4bbage** [comment]
I'm on a mac when running weevely, occurred a IOError. So I fix him.

**Comment by epinna** [comment]
Installing editline before python readline should fix this (see #7), but it does not succeed, so your hack it's welcome.

**Comment by c4bbage** [comment]
Readline module was installed

**Comment by c4bbage** [comment]
Ok, this is a small problem.

**Comment by epinna** [comment]
I confirm that readline does not fix this, this is why I included your patch - many thanks for your help

**Pull request merged**
