### PR TITLE
Add some CLI options

### PR DESCRIPTION
**Pull request by rsrdesarrollo**
fix https://github.com/epinna/weevely3/issues/103. fix https://github.com/epinna/weevely3/issues/137. fix https://github.com/epinna/weevely3/issues/29. Add CLI options to specify headers, proxy and basic authentication whitout the need of touching config file

### CODE REVIEW

**Comment by rsrdesarrollo** [comment]
This PR adds the following CLI options to the terminal command

```
  -H HEADERS, --header HEADERS
                        (HTTP) Extra header to include in the request. This option can be used multiple times to add/replace/remove multiple headers.
  -x PROXY, --proxy PROXY
                        Use a specific proxy [protocol://]host[:port].
  -u USER, --user USER  <user:password> server user and password for basic auth
```

the interface is the same as curl

**Comment by ZanyMonk** [comment]
Good idea !

There is one thing that bother me though : there is no `default=[]` for headers,it's undefined when starting a new session and that raises an Exception. Could you add a default value to this argument please ?

**Comment by rsrdesarrollo** [comment]
Sorry I fu*k*d up my repo (for reasons I'm ashamed to tell) xDD, I will generate a new PR, is easier than recovering the history of my broken repo xD

**Comment by noraj** [comment]
@rsrdesarrollo I would be nice you PR this again :)

**Pull request closed without merging**
