### PR TITLE
fixes to scripts

### PR DESCRIPTION
**Pull request by samueloph**
Make cgi.sh executable and add shebang to disablefuncionbypass.py

Thanks

### CODE REVIEW

**Comment by samueloph** [comment]
Wait, please hold on the merging of this, i think there may be something wrong with using `/bin/env` as a interpreter. It looks like on debian the env executable is at `/usr/bin/env`, and i bet on Kali and Ubuntu too.

Now i'm not sure if this change won't break things, AFAIK the `linuxprivchecker.py` script may be broken already because it is using `/bin/env`, and any calls to that not explicitly calling the interpreter may not work.

**Comment by epinna** [comment]
Hello Samuel,

Both files are not meant to be executed directly, so no need to be executable. Precisely, `cgi.sh` is supposed to be uploaded on the server so no need to be `+x`, while `disablefunctionbypass.py` is a module loded by weevely, so it doesn't need the shebang to be interpreted. 

Also, as you noticed, not sure if `/bin/env` is a portable shebang (I usually use `/usr/bin/env`).

Thanks anyway!

**Comment by samueloph** [comment]
@epinna Thanks, everything ok then. 
I'll be uploading weevely to Debian unstable today.

**Comment by epinna** [comment]
Please take a look at #89 .

**Pull request closed without merging**
